import { type NextPage } from "next";
import Head from "next/head";
import { User } from "~/types/User";

import { createContext, useContext, useState } from "react";
import LoginComponent from "~/Components/LoginPage/LoginComponent";

export const UserContext = createContext<User | null>(null);

const Home: NextPage = () => {
  const [user, setUser] = useState<User | null>(null);
  const [isLoading, setLoading] = useState(false);
  if (isLoading) {
    return <div>Loading...</div>;
  }

  // Show login screen if user is not defined
  if(!user) {
    return <LoginComponent setUser={setUser} setLoading={setLoading}/>
  }
  // Main App UI
  return (
    <UserContext.Provider value={user}>
      <Head>
        <title>Course Binder</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          Hello {user.name}!
          <button onClick={() => setUser(null)}>Logout</button>
          <SampleChild/>
        </div>
      </main>
    </UserContext.Provider>
  );
};

export default Home;

const SampleChild = () => {
  const user = useContext(UserContext);
  return <div>Hello {user?.name}! from child. You are a {user?.role}.</div>
}
